### ISSUE TITLE
The "for_each" value depends on resource attributes that cannot be determined until apply

### ISSUE THREAD

**Issue by goetzc** [terraform-aws-modules/terraform-aws-route53#59] opened 2021-10-04 18:24 UTC
## Description

Hello. When using the latest module version and running the plan to create a _record_ based on the value of a CloudFront distribution created using a _for_each_: 

```tf
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "2.3.0"

  …

  zone_id = local.dns_zone_id
  depends_on = [module.cloudfront]

  records = [
    {
      name = ""
      type = "A"
      alias = {
        name    = module.cloudfront.web.cloudfront_distribution_domain_name
        zone_id = module.cloudfront.web.cloudfront_distribution_hosted_zone_id
      }
    }
  ]
```

The plan fails with the following error when running locally or on Terraform Cloud:

```tf
Configuring remote state backend...
Initializing Terraform configuration...
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/records/modules/records/main.tf line 32, in resource "aws_route53_record" "this":
│   32:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})
│     ├────────────────
│     │ local.recordsets will be known only after apply
│     │ var.create is true
│     │ var.zone_id is "ZLHLLCNNHTTH8"
│     │ var.zone_name is null
│
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
```

## Versions
```
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.61.0
```

## Reproduction
- Are you using workspaces?: Yes
- Have you cleared the local cache: Yes and this error is even shows in TF Cloud.

### Code Snippet to Reproduce
Additionally to the above code, this is the extra relevant part:

`main.tf`
```tf
module "cloudfront" {
  source = "./modules/aws-cloudfront"

  for_each = {
    for k, v in var.projects : k => v
    if v.cdn
  }

  …
```
`varaibles.tf`
```tf
variable "projects" {
  type        = map(map(string))
  default = {
    "web" = {
      name = "…",
      cdn  = true,
    },
  }
}
```

## Expected behavior
The plan should end successfully.

## Actual behavior
The error is shown in the "plan" state and thus the apply is impossible.

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/2220440/135898952-85180c6b-c5ae-4fe1-8a37-da87f9c1f46d.png)

## Workaround
On local backend, the `-target` argument can be used to first plan and apply the dependencies. On Terraform Cloud there is the `TF_CLI_ARGS_plan` environment variable, which is supported since [version 0.13](https://github.com/hashicorp/terraform/blob/v0.13/CHANGELOG.md), e.g.:
`TF_CLI_ARGS_plan="-target=module.cloudfront"`

## Additional context
When first creating the AWS CloudFront dependency, then the records can be planned correctly, as the resources now exists. But running per parts is not ideal.

The error is about "`local.recordsets will be known only after apply`". I wonder if it is possible to have this refactor to avoid the `for_each` issue, or if this is a deeper rooted Terraform limitation?
https://github.com/terraform-aws-modules/terraform-aws-route53/blob/533f07d83f3993a9ca191d200f49caba71114aa9/modules/records/main.tf#L15-L20

Thanks.

**Comment by antonbabenko** [comment] 2021-10-04 18:52
This is, unfortunately, the valid behavior of Terraform still.

You even gave Terraform a hint by using `depends_on` inside of the module block but it does not help. I don't know any better workaround for this issue but I would like to figure it out and implement it.

**Comment by dmytro-dorofeiev** [comment] 2021-10-05 15:09
I can also confirm, I have the same issue after upgrade from 1.11.0 version to 2.3.0.

*main.tf*
```
module "records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 2.0"

  zone_name = keys(module.zones.route53_zone_zone_id)[0]

  records = [
    {
      name = "admin-ui"
      type = "A"
      alias = {
        name    =  module.alb.dns_name
        zone_id = module.alb.zone_id
      }
      allow_overwrite = true
    },
    {
      name = "customer-ui"
      type = "A"
      alias = {
        name    = module.alb.dns_name 
        zone_id = module.alb.zone_id
      }
      allow_overwrite = true
    },
  ]

  depends_on = [module.alb]
}
```

Receive output:
```
╷
│ Error: Invalid for_each argument
│ 
│   on .terraform/modules/records/modules/records/main.tf line 32, in resource "aws_route53_record" "this":
│   32:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})
│     ├────────────────
│     │ local.recordsets will be known only after apply
│     │ var.create is true
│     │ var.zone_id is null
│     │ var.zone_name is "qa.example.com"
│ 
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
```

When I replace in 2.3.0 two strings from 1.11.0 it works correctly
https://github.com/terraform-aws-modules/terraform-aws-route53/blob/v1.11.0/modules/records/main.tf#L3
https://github.com/terraform-aws-modules/terraform-aws-route53/blob/v1.11.0/modules/records/main.tf#L22

**Comment by whiteley** [comment] 2021-10-12 17:17
We had success downgrading to `2.0.0` and breakage with `2.1.0` (and all newer versions) suggesting the issue is isolated to https://github.com/terraform-aws-modules/terraform-aws-route53/commit/def532747d9d96303738f01f5e18b2c568071f0e.

**Comment by antonbabenko** [comment] 2021-10-12 19:27
Probably, it is related to `jsondecode()` and def5327 but WHYYY? :) And how to make it work?

I don't know the answer myself. If anyone has a working solution, please open a PR, and let's try to get it to work for terragrunt and terraform users.

**Comment by goetzc** [comment] 2021-10-15 00:10
I'm not sure if this is a use case for a `dynamic` block:
https://www.terraform.io/docs/language/expressions/dynamic-blocks.html

**Comment by anonymousobject** [comment] 2021-11-01 13:51
Just dropping in to say I do not believe it is specific to `jsondecode`. I modified the module to remove any json en/decoding and I still get that error. Also, it seems to be specific to `for_each`. I further modified the code to use the old `count` style of iterating `aws_route53_record` and I encountered no errors. Unfortunately, I did not find a fix to continue using `for_each`.

**Comment by abcfy2** [comment] 2021-12-03 03:23
Seem issue here. Will this will be fixed?

**Comment by gallowaystorm** [comment] 2021-12-20 21:05
Is this going to be fixed anytime soon?

**Comment by antonbabenko** [comment] 2021-12-21 08:48
I am not sure how to fix this. If anyone has a possibility to look into this, please open a PR where this is implemented correctly for all cases (to begin with, `examples/complete` should work).

**Comment by abcfy2** [comment] 2021-12-21 14:02
> I am not sure how to fix this. If anyone has a possibility to look into this, please open a PR where this is implemented correctly for all cases (to begin with, `examples/complete` should work).

Maybe we should fallback to `2.0.0`?

**Comment by antonbabenko** [comment] 2021-12-21 14:25
`jsondecode` (or another workaround) is necessary to avoid multiple calls to the same module (e.g. when using terragrunt).

**Comment by gallowaystorm** [comment] 2021-12-21 16:05
> I am not sure how to fix this. If anyone has a possibility to look into this, please open a PR where this is implemented correctly for all cases (to begin with, `examples/complete` should work).

In my use case:

```terraform
resource "aws_route53_record" "vanity_route53_cert_validation" {
  # use domain management secondary aws provider
  provider = aws.domain-management

  for_each = {
    # Grabs values of certificates for validation records only needed in domain management account by filtering for ones that includes var.fully_qualified_domain_name
    for dvo in aws_acm_certificate.vanity_certificate.domain_validation_options : dvo.domain_name => dvo if contains(values(dvo), var.fully_qualified_domain_name)
  }

  zone_id         = data.aws_route53_zone.vanity_zone.zone_id
  name            = each.value.resource_record_name
  records         = [each.value.resource_record_value]
  ttl             = 60
  type            = each.value.resource_record_type
  allow_overwrite = true
}
```


The "contains() function is what is messing me up"  I am trying to create a record in a seperate account for a vanity certificate.  To do so, I need to filter the domain_validation_options based off FQDN.  This contains() function is apparenrently not evaluated on plan, so it fails with:

```bash
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target
│ argument to first apply only the resources that the for_each depends on.
```


This doesn't make sense to me because if I went with the "classic" way of doing Certificate validation that is listed here on Terraform's site:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate

```terraform
resource "aws_route53_record" "example" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.example.zone_id
}
```


This ends up working... Even though it depends on a resource attribute that cannot be determined until applied.  Just like the error message above.

**Comment by sanguis** [comment] 2022-01-05 20:09
Confirmed on terragrunt. Removing the `jsonencode` and reverting to v2.0.0

**Comment by flora-five** [comment] 2022-01-06 14:46
I would like to suggest a possible solution and I have prepared a draft PR #64.

When any attribute of a record depends on resources that have to be created, `jsonencode` makes the entire `var.records` a value that is not known yet and Terraform cannot use it to make a plan.

The idea of the proposed solution is to allow the caller of the records module to pass to it, in another variable, a list with fully-known keys that the module can use for its internal map. This list, with fully-known keys, allows Terraform to build the plan.

**Comment by goetzc** [comment] 2022-02-06 01:00
> Confirmed on terragrunt. Removing the `jsonencode` and reverting to v2.0.0

I can confirm that old v2.0.0 works great.

**Comment by CumpsD** [comment] 2022-02-19 16:21
Ran into this right now as well

**Comment by CumpsD** [comment] 2022-02-19 16:30
I reverted this commit on `2.5.0` and the error is gone: https://github.com/terraform-aws-modules/terraform-aws-route53/commit/def532747d9d96303738f01f5e18b2c568071f0e

```
locals {
  # terragrunt users have to provide `records` as jsonencode()'d string.
  # See details: https://github.com/gruntwork-io/terragrunt/issues/1211
  // records = try(jsondecode(var.records), var.records)

  # Convert `records` from list to map with unique keys
  #
  # A list of `records` values is jsonencode()'d to a string to solve issue:
  # The true result value has the wrong type:
  # element types must all match for conversion to map.
  # Ref:
  # https://github.com/terraform-aws-modules/terraform-aws-route53/issues/47
  # https://github.com/terraform-aws-modules/terraform-aws-route53/pull/39

  recordsets = {
    for rs in var.records :
    join(" ", compact(["${rs.name} ${rs.type}", lookup(rs, "set_identifier", "")])) => merge(rs, {
      records = jsonencode(try(rs.records, null))
    })
  }
}
```

**Comment by SergeyShcherbakov1** [comment] 2022-03-05 13:19
> I reverted this commit on `2.5.0` and the error is gone: [def5327](https://github.com/terraform-aws-modules/terraform-aws-route53/commit/def532747d9d96303738f01f5e18b2c568071f0e)

I can confirm that this issue is present on ```2.5.0```. @CumpsD [CumpsD](https://github.com/CumpsD)'s suggestion worked for me.

Pure Terraform (no Terragrunt): ```v1.1.7```
AWS Provider: ```v4.4.0```

**Comment by jefferson-nagro** [comment] 2022-04-27 15:57
> > I reverted this commit on `2.5.0` and the error is gone: [def5327](https://github.com/terraform-aws-modules/terraform-aws-route53/commit/def532747d9d96303738f01f5e18b2c568071f0e)
> 
> I can confirm that this issue is present on `2.5.0`. [CumpsD](https://github.com/CumpsD)'s suggestion worked for me.
> 
> Pure Terraform (no Terragrunt): `v1.1.7` AWS Provider: `v4.4.0`

Work same for me.

**Comment by air3ijai** [comment] 2022-04-30 18:56
[module route53/records](https://registry.terraform.io/modules/terraform-aws-modules/route53/aws/latest/submodules/records?tab=inputs) - can't create DNS records by using `zone_id`, only by `zone_name`
```
module "delegation_records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 2.6"

  zone_id = "XXXXXXXXXXXXXXXXXXXXX"
  records = [
    {
      name    = local.zone_prefix
      type    = "NS"
      ttl     = var.ns_ttl
      records = module.zones[0].route53_zone_name_servers[local.zone_name]
    }
  ] 
}
```


```
│ Error: Invalid for_each argument
│
│   on .terraform/modules/delegation_records/modules/records/main.tf line 32, in resource "aws_route53_record" "this":
│   32:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})
│     ├────────────────
│     │ local.recordsets will be known only after apply
│     │ var.create is true
│     │ var.zone_id is "XXXXXXXXXXXXXXXXXXXXX"
│     │ var.zone_name is null
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument
│ to first apply only the resources that the for_each depends on.
╵
```

**Comment by air3ijai** [comment] 2022-05-01 05:15
Same issue with other resource dependency. It start to work only after resource `random_string` is created.
Also, it works fine with a regular resource.

**Base code**
```
# DNS zone
module "zones" {
  source  = "terraform-aws-modules/route53/aws//modules/zones"
  version = "2.6.0"

  zones = {
    "test.tld" = {
    }
  }
}

# Random prefix
resource "random_string" "test" {
  length  = 5
  special = false
}
```

**Resource - ok**
```
# DNS records - resource
resource "aws_route53_record" "test" {
  zone_id = var.zone_id
  name    = "test-${random_string.test.result}"
  type    = "A"
  records = ["1.1.1.1"]
}
```

**Module - issue**
```
# DNS records - module
module "records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "2.6.0"

  zone_name = "test.tld"
  records = [
    {
      name    = "test-${random_string.test.result}"
      type    = "A"
      records = ["1.1.1.1"]
    }
  ]
  depends_on = [
    module.zones,
    random_string.test
  ]
}
```

**Error**
```
╷
│ Error: Invalid for_each argument
│
│   on .terraform/modules/records/modules/records/main.tf line 32, in resource "aws_route53_record" "this":
│   32:   for_each = var.create && (var.zone_id != null || var.zone_name != null) ? local.recordsets : tomap({})
│     ├────────────────
│     │ local.recordsets will be known only after apply
│     │ var.create is true
│     │ var.zone_id is null
│     │ var.zone_name is "test.tld"
│
│ The "for_each" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work around this, use the -target argument
│ to first apply only the resources that the for_each depends on.
```

**Comment by maltyxx** [comment] 2022-05-12 20:22
Same problem I have downgrade to version 2.0.0.

**Comment by vtzan** [comment] 2022-06-15 14:40
any update on this please? thanks

**Comment by antonbabenko** [comment] 2022-06-15 14:44
@vtzan Not yet. Hopefully, during this week, it will be improved.

**Comment by vtzan** [comment] 2022-06-15 14:55
> @vtzan Not yet. Hopefully, during this week, it will be improved.

Great news! Thank you @antonbabenko for your reply

**Comment by flora-five** [comment] 2022-06-17 19:16
@antonbabenko There was a proposed solution in PR #64, but that PR has been closed automatically due to staleness. Just a gentle reminder about it, in case there isn't a better solution.

**Comment by antonbabenko** [comment] 2022-06-18 20:29
@vtzan I give up (for at least a couple of months). I tried to fix it for several hours more, involving @bryantbiggs, but it is still not working as we need. I opened #72 and added the explanation for anyone willing to give it a try.

@flora-five #64 is rather close, but I am not sure it is going to work with all examples. Also, it would be great if it did not introduce a new unnecessary/verbose variable (record_map_keys).

**Comment by antonbabenko** [comment] 2022-06-19 11:28
This issue has been resolved in version 2.8.1 :tada:

**Closed** 2022-06-19 11:27 UTC

**Comment by antonbabenko** [comment] 2022-06-19 11:30
Please give it a try! Big thanks to @flora-five for the final touch that fixed the unfixable :)

**Comment by vtzan** [comment] 2022-06-19 12:19
Dear @antonbabenko @flora-five this is working great! Thanks alot for the fix.
