### ISSUE TITLE
Multiple records return error: element types must all match for conversion to map

### ISSUE THREAD

**Issue by 1mamute** [terraform-aws-modules/terraform-aws-route53#50] opened 2021-06-27 15:41 UTC
## Description

Hi, I created a hosted zone using the modules/zones and now I'm trying to create multiple records for this zone using the modules/records.  These records are simple CNAME, MX, TXT, etc...  

Can someone provide some insight on what I am doing wrong?

## Versions

 - **Terraform**: v1.0.0

 - **Provider(s)**:  hashicorp/aws v3.47.0

 - **Module**: terraform-aws-modules/route53/aws v2.1.0

## Reproduction
The hosted zone:
```
module "zones" {
  source  = "terraform-aws-modules/route53/aws//modules/zones"
  version = "2.1.0"

  zones = {
    "example.org" = {
      tags = {
        Environment = "main"
      }
    }
  }
}
```

The records:
```
module "records_souadiferenca_org" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "2.1.0"

  zone_id    = module.zones.route53_zone_zone_id["example.org"]
  depends_on = [module.zones]

  records = [
    {
      name    = "www"
      type    = "CNAME"
      ttl     = 5
      records = ["example.org"]
    },
    {
      name    = ""
      type    = "MX"
      ttl     = 5
      records = ["10 mx.zoho.com", "20 mx2.zoho.com", "50 mx3.zoho.com"]
    },
    {
      name    = ""
      type    = "TXT"
      ttl     = 300
      records = ["zoho-verification=example.zoho.com"]
    },
    {
      name = ""
      type = "NS"
      ttl  = 172800
      records = [
        module.zones.route53_zone_name_servers["example.org"][0],
        module.zones.route53_zone_name_servers["example.org"][1],
        module.zones.route53_zone_name_servers["example.org"][2],
        module.zones.route53_zone_name_servers["example.org"][3],
      ]
    }
  ]
}
```

P.S.: I tried replacing the `module.zones.route53_zone_name_servers["example.org"][0]` with the actual NS records and it didn't worked as well. The `module.zones.route53_zone_name_servers["example.org"][0]` does indeed returns the name_servers from the hosted zone. The terraform console output of [0] is: `"ns-1304.awsdns-35.org"`, it is apparently a string.

## Expected behavior and Actual behavior
It should create the records. Looks like the variables are the same type of one another.  
The output is `Error: Inconsistent conditional result types` and `The true result value has the wrong type: element types must all match for conversion to map.` as the screenshot below shows.  

Seems likes the module is not correctly converting all the records to the **for_each** tomap({}) function.  

### Terminal Output Screenshot(s)
![image](https://user-images.githubusercontent.com/22196761/123550295-48da9f80-d743-11eb-855d-d624f187128d.png)

**Comment by antonbabenko** [comment] 2021-06-28 08:48
Hi @1mamute !

Thanks for the example code that does not work for you!

There is already a similar issue discussed in #39 and it doesn't seem that we understand how to fix it for all versions starting from 0.13 because it seems to have different behavior in 0.14 and 0.15.

Closing this as a duplicate of #39

**Closed by antonbabenko** 2021-06-28 08:48 UTC
